# Generated by Django 4.2 on 2023-04-23 18:46

from django.db import migrations, models
import marins.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('is_open', models.BooleanField(default=True)),
                ('location', models.CharField(choices=[('Haifa', 'Haifa'), ('Herzliya', 'Herzliya'), ('Tel-Aviv', 'Tel-Aviv'), ('Ashdod', 'Ashdod'), ('Ashkelon', 'Ashkelon'), ('Eilat', 'Eilat')], max_length=100)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=marins.models.upload_image_path)),
                ('max_vessels', models.IntegerField(default=1)),
                ('slug', models.SlugField(default='')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
