# Generated by Django 4.2 on 2023-04-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marin',
            old_name='name',
            new_name='title',
        ),
    ]
